TRUNCATE users CASCADE;
TRUNCATE campaigns CASCADE;
TRUNCATE experiments CASCADE;
TRUNCATE buckets CASCADE;
TRUNCATE bucket_users CASCADE;
TRUNCATE campaign_users CASCADE;
TRUNCATE campaign_experiments CASCADE;
TRUNCATE experiment_buckets CASCADE;
TRUNCATE events CASCADE;
