steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=gcr.io/$PROJECT_ID/sweetspot:latest
      - --tag=gcr.io/$PROJECT_ID/sweetspot:$SHORT_SHA
      - --cache-from=gcr.io/$PROJECT_ID/sweetspot:latest
      - .
images:
  - gcr.io/$PROJECT_ID/sweetspot:$SHORT_SHA
  - gcr.io/$PROJECT_ID/sweetspot:latest
timeout: 30m
options:
  machineType: N1_HIGHCPU_8
