steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        docker pull gcr.io/$PROJECT_ID/sweetspot:latest || exit 0
  # build the container image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag
      - gcr.io/$PROJECT_ID/sweetspot:$SHORT_SHA
      - --cache-from
      - gcr.io/$PROJECT_ID/sweetspot:latest
      - .
  # push the container image to Container Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/sweetspot:$SHORT_SHA
  # Deploy container image to Cloud Run
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - sweetspot
      - --image
      - gcr.io/$PROJECT_ID/sweetspot:$SHORT_SHA
      - --region
      - europe-west1
      - --platform
      - managed
images:
  - gcr.io/$PROJECT_ID/sweetspot:$SHORT_SHA
timeout: 1800s
options:
  machineType: N1_HIGHCPU_32
