steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker pull gcr.io/$PROJECT_ID/sweetspot:latest || exit 0
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/sweetspot:latest",
        "--cache-from=gcr.io/$PROJECT_ID/sweetspot:latest",
        "--machine-type=n1-highcpu-8",
        "--timeout=30m",
        ".",
      ]
images: ["gcr.io/$PROJECT_ID/sweetspot:latest"]
