steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t gcr.io/$PROJECT_ID/sweetspot:latest
      - -t sweetspot:$SHORT_SHA
      - .
images:
 - gcr.io/$PROJECT_ID/sweetspot:latest
timeout: 30m
