version: '3'

services:
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/www/data
    ports:
      - 80:80
      - 443:443
    depends_on:
      - supple-api

  postgres-db:
    container_name: postgres-db
    restart: unless-stopped
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=supple
    volumes:
      - ./api/migrations:/docker-entrypoint-initdb.d

  supple-api:
    container_name: supple-api
    restart: unless-stopped
    build:
      context: api/build
    ports:
      - "8082:8082"
    depends_on:
      - postgres-db
