version: '3'

services:
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/www/data
    ports:
      - 80:80
      - 443:443
  postgres-db:
    container_name: postgres-db
    restart: unless-stopped
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=supple
    volumes:
      - ./api/migrations:/docker-entrypoint-initdb.d
