FROM fpco/stack-build:lts-14.27
WORKDIR /opt/build

# We depend on postgres
RUN apt-get update --quiet && apt-get install --yes --quiet libpq-dev

# Install deps first for improved caching
COPY ./api/stack.yaml .
COPY ./api/sweetspot.cabal .
RUN stack build --only-dependencies --verbosity warn
