version: '3'

services:
  postgres-db:
    container_name: postgres-db
    restart: unless-stopped
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=supple
    volumes:
      - ./server/migrations:/docker-entrypoint-initdb.d
