version: '3'

services:
  postgres-db:
    container_name: postgres-db
    restart: unless-stopped
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=supple

  supple-api:
    container_name: supple-api
    restart: unless-stopped
    links:
      - postgres-db
    build:
      context: '.'
    ports:
      - "8082:8082"
    depends_on:
      - postgres-db
    environment:
      - DB_HOST=postgres-db
      - DB_USER=postgres
      - DB_PORT=5432
      - DB_PASSWORD=
      - DB_NAME=supple
