version: "3"

services:
  postgres-db:
    container_name: postgres-db
    restart: unless-stopped
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=sweetspot
      - POSTGRES_USER=sweetspot

  sweetspot-api:
    container_name: sweetspot-api
    restart: unless-stopped
    links:
      - postgres-db
    build:
      context: "."
    ports:
      - "8082:8082"
    depends_on:
      - postgres-db
    env_file: api/.env
    environment:
      - DB_HOST=postgres-db
      - DB_NAME=sweetspot
      - DB_PASSWORD=
      - DB_PORT=5432
