#!/bin/bash
docker build --target build -t sweetspot-build .
docker tag sweetspot-build 586715926679.dkr.ecr.us-east-2.amazonaws.com/sweetspot-build
$(aws ecr get-login --no-include-email)
docker push 586715926679.dkr.ecr.us-east-2.amazonaws.com/sweetspot-build
