#!/bin/bash

echo "=> Watching & building PureScript injectables"
pulp --watch build --main Supple.Main --to ../dist/supple-inj.js &
pulp --watch build --main Supple.Checkout --to ../dist/supple-checkout.js &
