#!/bin/bash

set -e

print_filesize() {
  FILE_SIZE=$(du -k ./dist/$1 | cut -f1)
  echo "${FILE_SIZE}K -- $2"
}

echo "=> Building fulcrum"
START=$(date +%s)

spago bundle-app --main Fulcrum.Main --to fulcrum.js
echo "=> Finished building fulcrum"

# To include node modules in our bundle we need a bundler
yarn parcel build fulcrum.js --no-source-maps
mv dist/fulcrum.js dist/fulcrum.min.js
yarn parcel build fulcrum.js --no-minify --no-source-maps
rm fulcrum.js
echo "=> Finished bundling dependencies"

gzip --keep --force dist/fulcrum.min.js
echo "=> Finished compressing"

END=$(date +%s)
BUILD_TIME=$(( $END - $START ))
echo "=> Finished build in ${BUILD_TIME}s"
echo "=> Build size fulcrum:"
print_filesize "fulcrum.js" "Raw Output"
print_filesize "fulcrum.min.js" "Minified"
print_filesize "fulcrum.min.js.gz" "Minified and Compressed"
rm dist/fulcrum.min.js.gz
