#!/bin/bash

print_filesize() {
  FILE_SIZE=$(du -k ../dist/$1 | cut -f1)
  echo "${FILE_SIZE}K -- $2"
}

ENV=${1:-dev}
echo "=> Building PureScript injectables for ${ENV}"
START=$(date +%s)

# Source env vars
if [[ $ENV == "staging" ]]; then
  source .env.staging
elif [[ $ENV == "production" ]]; then
  source .env.production
fi

spago bundle-app --main SweetSpot.Main --to ./output/sweetspot-main.js
if [ $? -ne 0 ]; then
  echo "=> Failed to build main"
  exit 1
fi
echo "=> Finished building main"

npx --quiet uglify-js --compress --mangle --output ./output/sweetspot-main.min.js ./output/sweetspot-main.js
if [ $? -ne 0 ]; then
  echo "=> Failed to minify main"
  exit 1
fi

gzip --keep --force ./output/sweetspot-main.min.js
if [ $? -ne 0 ]; then
  echo "=> Failed to gzip main"
  exit 1
fi

mv ./output/sweetspot-main* ../dist/

END=$(date +%s)
BUILD_TIME=$(( $END - $START ))
echo "=> Finished build in ${BUILD_TIME}s"
echo "=> Build size main:"
print_filesize "sweetspot-main.js" "Raw Output"
print_filesize "sweetspot-main.min.js" "Minified"
print_filesize "sweetspot-main.min.js.gz" "Minified and Compressed"
rm ../dist/sweetspot-main.min.js.gz

spago bundle-app --main SweetSpot.Checkout --to ./output/sweetspot-checkout.js
if [ $? -ne 0 ]; then
  echo "=> Failed to build checkout"
  exit 1
fi

npx --quiet uglify-js --compress --mangle --output ./output/sweetspot-checkout.min.js ./output/sweetspot-checkout.js
if [ $? -ne 0 ]; then
  echo "=> Failed to minify checkout"
  exit 1
fi

gzip --keep --force ./output/sweetspot-checkout.min.js
if [ $? -ne 0 ]; then
  echo "=> Failed to gzip checkout"
  exit 1
fi

mv ./output/sweetspot-checkout* ../dist/

echo "=> Build size checkout:"
print_filesize "sweetspot-checkout.js" "Raw Output"
print_filesize "sweetspot-checkout.min.js" "Minified"
print_filesize "sweetspot-checkout.min.js.gz" "Minified and Compressed"
rm ../dist/sweetspot-checkout.min.js.gz

echo "=> Cleaning up cached gziped files"
rm ../dist/___dist_* | true
