#!/bin/bash

ENV=${1:-staging}
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
IMAGE_NAME="586715926679.dkr.ecr.us-east-2.amazonaws.com/sweetspot:${COMMIT}"

exit_on_failure() {
  if [ $? -ne 0 ]; then
    exit 1
  fi
}

echo "=> Deploying SweetSpot to ${ENV}"

# Figure out which commit to try and deploy
if [[ -z $2 ]]; then
  echo "=> No commit argument given, continuing with origin/master commit, which is"
  git fetch --quiet
  echo $(git show --oneline --quiet origin/master)
  COMMIT=$(git rev-parse --short origin/master)
else
  echo "=> Commit argument given: $2, which is"
  echo $(git show --oneline --quiet $2)
  COMMIT=$2
fi

echo "=> Checking commit has finished building"
IMAGE_META="$(aws ecr describe-images --repository-name=sweetspot --image-ids=imageTag=${COMMIT} 2> /dev/null)"

if [[ $? == 0 ]]; then
  echo "=> Build has finished, continuing deployment"
else
  echo "=> No image found by this tag, perhaps the build is still in progress"
  exit 1
fi

# Update sweetspot deployment to latest image
echo "=> Applying new image"
ecs deploy default sweetspot-${ENV} --tag ${COMMIT}
exit_on_failure
echo "=> Done!"
