name:                supple
version:             0.1.0.0
github:              "githubuser/supple"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

# extra-source-files:
# - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/supple#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- casing
- contravariant
- data-default
- envy
- fast-logger
- hasql
- lens
- lens-aeson
- load-env
- mtl
- purescript-bridge
- scientific
- servant
- servant-server
- text
- time
- transformers
- utf8-string
- wai
- wai-cors
- warp
- wreq
- hasql-pool

library:
  source-dirs: src

executables:
  supple-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - supple

  bridge-exe:
    main:                Main.hs
    source-dirs:         bridge
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - supple


tests:
  supple-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - supple
